# .streamlit/config.toml

[server]
runOnSave = true  # Enable auto-rerun when files are saved
maxUploadSize = 200  # In MB
maxMessageSize = 200  # In MB

[browser]
gatherUsageStats = false  # Disable usage statistics gathering

[theme]
# A modern, vibrant color palette
primaryColor="#00f9d3"
backgroundColor="#0a0f18"
secondaryBackgroundColor="#1c222e"
textColor="#ffffff"
font="sans serif"